server:
    port: 8080
spring:
    config:
        activate:
            on-profile: dev
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/htqlcv
        username: root
        password: 12345678
    mail:
        username: pnhtuanhcmus@gmail.com
        password: lqyfvmgttkxtltfu
        from: pnhtuanhcmus@gmail.com
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

