server:
    port: 8080
    forward-headers-strategy: native
spring:
    config:
        activate:
            on-profile: prod
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    data:
        redis:
            host: redis
            port: 6379
    datasource:
        url: jdbc:mysql://mysql:3306/htqlcv
        username: htqlcv
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
        username: pnhtuanhcmus@gmail.com
        password: lqyfvmgttkxtltfu
        from: pnhtuanhcmus@gmail.com
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

